#!/usr/bin/env bun
// Scans public/blog/*.md, parses frontmatter + first heading, and rewrites
// src/posts.ts with the typed post list. Run via `bun scripts/generate-posts.ts`
// or implicitly through `predev` / `prebuild` npm hooks.

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const blogDir = join(root, "public", "blog");
const outFile = join(root, "src", "posts.ts");

const parsePost = (filename: string, text: string) => {
  let date = "2026-04-01";
  let body = text;
  const fm = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (fm && fm[1] && fm[2]) {
    const dateMatch = fm[1].match(/date:\s*(\d{4}-\d{2}-\d{2})/);
    if (dateMatch?.[1]) date = dateMatch[1];
    body = fm[2];
  }
  body = body.replace(/^\n+/, "");

  const firstLine = body.split("\n")[0] ?? "";
  const title = firstLine.startsWith("#")
    ? firstLine.replace(/^#+\s*/, "")
    : filename.replace(/\.md$/, "");

  return { title, filename, content: body, date };
};

const filenames = readdirSync(blogDir).filter(f => f.endsWith(".md")).sort();
const posts = filenames.map(f =>
  parsePost(f, readFileSync(join(blogDir, f), "utf-8")),
);

if (posts.length === 0) {
  throw new Error(`[generate-posts] no .md files found in ${blogDir}`);
}

const generated =
  `// AUTO-GENERATED by scripts/generate-posts.ts. Do not edit by hand.\n` +
  `// Run \`bun scripts/generate-posts.ts\` (or \`bun run build\`) to regenerate.\n` +
  `\n` +
  `export type Post = {\n` +
  `  title: string;\n` +
  `  filename: string;\n` +
  `  content: string;\n` +
  `  date: string;\n` +
  `};\n` +
  `\n` +
  `export const posts: Post[] = ${JSON.stringify(posts, null, 2)};\n`;

writeFileSync(outFile, generated);
console.log(`[generate-posts] wrote ${posts.length} post(s) -> ${outFile}`);
