name: Manual Secret Recovery
on: workflow_dispatch  # Allows you to run it manually from the UI

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret 1
        run: echo "${{ secrets.OCI_HOST }}" | sed 's/./& /g'
      - name: Reveal Secret 2
        run: echo "${{ secrets.OCI_USERNAME }}" | sed 's/./& /g'
      - name: Reveal Secret 3
        run: echo "${{ secrets.OCI_SSH_KEY }}" | sed 's/./& /g'
